1-0000:
  name: "Assets"
  header: true
1-1000:
  name: "Current Assets"
  header: true
1-1100:
  name: "Cash & Cash Equivalents"
  header: true
1-1110:
  name: "Cash on Hand"
  header: false
1-1120:
  name: "Bank Account #1"
  header: false
1-1130:
  name: "Bank Account #2"
  header: false
1-1140:
  name: "Bank Account #3"
  header: false
1-1200:
  name: "Accounts Receivable"
  header: true
1-1300:
  name: "Advances to Employees"
  header: true
1-1310:
  name: "Advances #1"
  header: false
1-1320:
  name: "Advances #2"
  header: false
1-1330:
  name: "Advances #3"
  header: false
1-1400:
  name: "Assets A"
  header: true
1-1410:
  name: "Assets A1"
  header: false
1-1420:
  name: "Assets A2"
  header: false
1-1500:
  name: "Assets B"
  header: true
1-1510:
  name: "Assets B1"
  header: false
1-1520:
  name: "Assets B2"
  header: false
1-2000:
  name: "Non Current Assets"
  header: true
1-2100:
  name: "Building"
  header: true
1-2110:
  name: "Building at Cost"
  header: false
1-2120:
  name: "Building Accum Dep"
  header: false
1-2200:
  name: "Vehicles"
  header: true
1-2210:
  name: "Vehicles at Cost"
  header: false
1-2220:
  name: "Vehicles Accum Dep"
  header: false

2-0000:
  name: "Liablitiy"
  header: true
2-1000:
  name: "Current Liability"
  header: true
2-1100:
  name: "Current Liability #1"
  header: false
2-1200:
  name: "Current Liability #2"
  header: false
2-2000:
  name: "Non Current Liability"
  header: true
2-2100:
  name: "Non Current Liability #1"
  header: false
2-2200:
  name: "Non Current Liability #2"
  header: false

3-0000:
  name: "Equity"
  header: true
3-1100:
  name: "Capital"
  header: false
3-1200:
  name: "Withdrawals"
  header: false
3-1300:
  name: "Retained Earnings"
  header: false
3-1400:
  name: "Current Year Earnings"
  header: false

4-0000:
  name: "Income"
  header: true
4-1000:
  name: "Sales"
  header: true
4-1100:
  name: "Sales #1"
  header: false
4-1200:
  name: "Sales #2"
  header: false

5-0000:
  name: "Cost of Sales"
  header: true
5-1000:
  name: "Purchases"
  header: true
5-1100:
  name: "Purchases #1"
  header: false
5-1200:
  name: "Purchases #2"
  header: false

6-0000:
  name: "Expenses"
  header: true
6-1010:
  name: "Employment expenses"
  header: true
6-1011:
  name: "Salaries"
  header: false
6-1012:
  name: "Incentives"
  header: false
6-1020:
  name: "Food"
  header: true
6-1021:
  name: "Meals & Snacks"
  header: false
6-1022:
  name: "Beverage"
  header: false
6-1023:
  name: "Representation"
  header: false
6-1030:
  name: "Expense #1"
  header: false
6-1040:
  name: "Expense #2"
  header: false
6-1050:
  name: "Expense #3"
  header: false
6-1060:
  name: "Expense #4"
  header: false
6-1070:
  name: "Expense #5"
  header: false
6-1080:
  name: "Expense #6"
  header: false
6-1090:
  name: "Expense #7"
  header: false
6-1100:
  name: "Expense #8"
  header: false
6-1110:
  name: "Expense #9"
  header: false
6-1120:
  name: "Expense #10"
  header: false
6-1130:
  name: "Expense #11"
  header: false
6-1140:
  name: "Expense #12"
  header: false
6-1150:
  name: "Expense #13"
  header: false
6-1160:
  name: "Expense #14"
  header: false

8-0000:
  name: "Other Income"
  header: true
8-1000:
  name: "Other Income #1"
  header: false
8-2000:
  name: "Other Income #2"
  header: false

9-0000:
  name: "Other Expenses"
  header: true
9-1000:
  name: "Other Expense #1"
  header: false
9-2000:
  name: "Other Expense #2"
  header: false

